export const allFields = [
    { key: "estudiante.cedulaEstudiante", label: "Cédula Estudiante" },
    { key: "estudiante.nombresEstudiante", label: "Nombres" },
    { key: "estudiante.apellidosEstudiante", label: "Apellidos" },
    { key: "estudiante.genero", label: "Genero" },
    { key: "estudiante.fechaNacimientoEstudiante", label: "Fecha de Nacimiento" },
    { key: "estudiante.emailEstudiante", label: "Correo Estudiante" },
    { key: "estudiante.numHermanos", label: "Número de Hermanos" },
    { key: "estudiante.ordenNacimiento", label: "Orden de Nacimiento" },
    { key: "estudiante.gustos", label: "Gustos" },
    { key: "estudiante.disgusta", label: "Le Disgusta" },
    { key: "estudiante.alergia", label: "¿Tiene Alergia?" },
    { key: "estudiante.alergiaDetalle", label: "Detalle de Alergia" },
    { key: "estudiante.enfermedad", label: "¿Tiene Enfermedad?" },
    { key: "estudiante.nombreEnfermedad", label: "Nombre de Enfermedad" },
    { key: "estudiante.tratamiento", label: "¿Sigue Tratamiento?" },
    { key: "estudiante.tratamientoDetalle", label: "Detalle de Tratamiento" },
    { key: "informacionAcademica.seleccionNiveles", label: "Nivel" },
    { key: "informacionAcademica.seleccionHorario", label: "Jornada" },
    { key: "informacionAcademica.modalidad", label: "Modalidad" },
    { key: "ingresoRetiro.ingreso", label: "Ingreso" },
    { key: "personaAutorizada.nombrePersonaAutorizada", label: "Persona Autorizada" },
    { key: "personaAutorizada.telefonoPersonaAutorizada", label: "Telefono Persona Autorizada" },
    { key: "personaAutorizada.retiroPorOtraPersona", label: "¿Retiro por otra persona?" },
    { key: "personaAutorizada.salida", label: "Forma de salida" },
    { key: "madre.nombreMadre", label: "Nombre Madre" },
    { key: "madre.cedulaMadre", label: "Cédula Madre" },
    { key: "madre.telefonoMadre", label: "Telefono Madre" },
    { key: "madre.emailMadre", label: "Email Madre" },
    { key: "padre.nombrePadre", label: "Nombre Padre" },
    { key: "padre.cedulaPadre", label: "Cedula Padre" },
    { key: "padre.telefonoPadre", label: "Telefono Padre" },
    { key: "padre.emailPadre", label: "Email del Padre" },
    { key: "representante.nombreRepresentante", label: "Representante Legal" },
    { key: "representante.telefonoRepresentante", label: "Telefono Representante" },
  ];